"""
Supabase Strategy Agent for QuantumTrade Platform
Generates buy/sell/hold signals based on various technical indicators and strategies
Integrates with Supabase for data persistence and configuration
"""

import random
import logging
from typing import Dict, List, Optional
from datetime import datetime
import math
import pandas as pd
import os

from ..database.supabase_client import get_supabase_client
from ..database.supabase_models import StrategyConfiguration, StrategyExecution
from ..core.model_server import load_model, predict

logger = logging.getLogger(__name__)
supabase = get_supabase_client()


MODEL_NAME = os.getenv("STRATEGY_MODEL", "rf_v1")


class SupabaseStrategyAgent:
    """
    Generates buy/sell/hold signals based on various technical indicators and strategies
    Integrates with Supabase for data persistence and configuration
    """

    def __init__(self, user_id: str, symbol: str = "BTC-USD", strategy: str = "random"):
        self.user_id = user_id
        self.symbol = symbol
        self.strategy = strategy
        self.price_history = []
        self.config = self._load_strategy_config()
        self.model = None
        try:
            self.model = load_model(MODEL_NAME)
        except Exception:
            self.model = None

    def _load_strategy_config(self) -> Dict:
        """
        Load strategy configuration from Supabase

        Returns:
            Strategy configuration dictionary
        """
        try:
            response = (
                supabase.table("strategy_configurations")
                .select("*")
                .eq("user_id", self.user_id)
                .eq("strategy_name", self.strategy)
                .eq("asset", self.symbol)
                .execute()
            )

            if response.data and len(response.data) > 0:
                config_data = response.data[0]
                return config_data.get("config", {})
            else:
                # Return default configuration
                return self._get_default_config()
        except Exception as e:
            logger.error(f"Error loading strategy config: {e}")
            return self._get_default_config()

    def _get_default_config(self) -> Dict:
        """
        Get default configuration for the strategy

        Returns:
            Default configuration dictionary
        """
        default_configs = {
            "moving_average": {"short_period": 5, "long_period": 20},
            "rsi": {"period": 14, "overbought": 70, "oversold": 30},
            "breakout": {"period": 20, "threshold": 0.05},
            "mean_reversion": {"period": 20, "z_score_threshold": 1.0},
            "macd": {"fast_period": 12, "slow_period": 26, "signal_period": 9},
            "bollinger_bands": {"period": 20, "std_dev": 2.0},
            "random": {},
        }
        return default_configs.get(self.strategy, {})

    def _save_strategy_config(self, config: Dict) -> bool:
        """
        Save strategy configuration to Supabase

        Args:
            config: Configuration to save

        Returns:
            True if successful, False otherwise
        """
        try:
            # First, try to update existing record
            response = (
                supabase.table("strategy_configurations")
                .update({"config": config, "updated_at": datetime.utcnow().isoformat()})
                .eq("user_id", self.user_id)
                .eq("strategy_name", self.strategy)
                .eq("asset", self.symbol)
                .execute()
            )

            # If no record was updated, create a new one
            if not response.data:
                response = (
                    supabase.table("strategy_configurations")
                    .insert(
                        {
                            "user_id": self.user_id,
                            "strategy_name": self.strategy,
                            "asset": self.symbol,
                            "is_active": True,
                            "config": config,
                            "created_at": datetime.utcnow().isoformat(),
                            "updated_at": datetime.utcnow().isoformat(),
                        }
                    )
                    .execute()
                )

            return True
        except Exception as e:
            logger.error(f"Error saving strategy config: {e}")
            return False

    def _save_strategy_execution(self, signal: Dict) -> bool:
        """
        Save strategy execution to Supabase

        Args:
            signal: Signal generated by the strategy

        Returns:
            True if successful, False otherwise
        """
        try:
            execution_data = {
                "user_id": self.user_id,
                "strategy_name": self.strategy,
                "asset": self.symbol,
                "signal": signal["action"],
                "confidence": signal.get("confidence", 0.0),
                "executed_at": datetime.utcnow().isoformat(),
            }

            response = (
                supabase.table("strategy_executions").insert(execution_data).execute()
            )
            return True
        except Exception as e:
            logger.error(f"Error saving strategy execution: {e}")
            return False

    def generate_signal(self, price_data: Dict = None) -> Dict:
        """
        Generate trading signal based on selected strategy

        Args:
            price_data: Dictionary containing current price information

        Returns:
            Dictionary with signal information
        """
        try:
            # Update price history
            if price_data and "price" in price_data:
                self.price_history.append(
                    {
                        "price": price_data["price"],
                        "timestamp": datetime.utcnow(),
                        "open": price_data.get("open", price_data["price"]),
                        "high": price_data.get("high", price_data["price"]),
                        "low": price_data.get("low", price_data["price"]),
                        "close": price_data.get("close", price_data["price"]),
                        "volume": price_data.get("volume", 0),
                    }
                )

                # Keep only last 100 data points
                if len(self.price_history) > 100:
                    self.price_history = self.price_history[-100:]

            # Use model if available
            if self.model and len(self.price_history) > 20:
                # Convert price history to DataFrame for model prediction
                prices = [p["price"] for p in self.price_history]
                df = pd.DataFrame({"price": prices})
                pred = predict(self.model, df)
                if pred == 1:
                    signal = {"action": "BUY", "size": 1.0, "confidence": 0.8}
                else:
                    signal = {"action": "SELL", "size": 1.0, "confidence": 0.8}
            else:
                # Generate signal based on strategy
                if self.strategy == "random":
                    signal = self._random_strategy()
                elif self.strategy == "moving_average":
                    signal = self._moving_average_strategy()
                elif self.strategy == "rsi":
                    signal = self._rsi_strategy()
                elif self.strategy == "breakout":
                    signal = self._breakout_strategy()
                elif self.strategy == "mean_reversion":
                    signal = self._mean_reversion_strategy()
                elif self.strategy == "macd":
                    signal = self._macd_strategy()
                elif self.strategy == "bollinger_bands":
                    signal = self._bollinger_bands_strategy()
                else:
                    signal = self._random_strategy()

            # Add metadata
            signal_data = {
                "symbol": self.symbol,
                "strategy": self.strategy,
                "action": signal["action"],
                "size": signal.get("size", 1.0),
                "confidence": signal.get("confidence", 0.5),
                "timestamp": datetime.utcnow().isoformat(),
            }

            # Save execution to Supabase
            self._save_strategy_execution(signal_data)

            return signal_data

        except Exception as e:
            logger.error(f"Error generating signal: {e}")
            return {
                "symbol": self.symbol,
                "strategy": self.strategy,
                "action": "HOLD",
                "size": 0.0,
                "confidence": 0.0,
                "timestamp": datetime.utcnow().isoformat(),
            }

    def _random_strategy(self) -> Dict:
        """Random signal generation strategy"""
        action = random.choice(["BUY", "SELL", "HOLD"])
        size = random.uniform(0.1, 1.0)
        confidence = random.uniform(0.3, 0.8)

        return {"action": action, "size": size, "confidence": confidence}

    def _moving_average_strategy(self) -> Dict:
        """Moving average crossover strategy"""
        if len(self.price_history) < 20:
            return self._random_strategy()

        # Get configuration
        short_period = self.config.get("short_period", 5)
        long_period = self.config.get("long_period", 20)

        # Calculate simple moving averages
        prices = [p["price"] for p in self.price_history[-long_period:]]
        short_ma = sum(prices[-short_period:]) / short_period
        long_ma = sum(prices) / long_period

        # Generate signal based on MA crossover
        if short_ma > long_ma:
            action = "BUY"
            confidence = min(
                1.0, (short_ma - long_ma) / long_ma * 10
            )  # Scale confidence
        elif short_ma < long_ma:
            action = "SELL"
            confidence = min(1.0, (long_ma - short_ma) / long_ma * 10)
        else:
            action = "HOLD"
            confidence = 0.1

        size = min(1.0, confidence * 2)  # Size based on confidence

        return {"action": action, "size": size, "confidence": confidence}

    def _rsi_strategy(self) -> Dict:
        """Relative Strength Index strategy"""
        period = self.config.get("period", 14)
        overbought = self.config.get("overbought", 70)
        oversold = self.config.get("oversold", 30)

        if len(self.price_history) < period + 1:
            return self._random_strategy()

        # Calculate RSI
        prices = [p["price"] for p in self.price_history[-(period + 1) :]]
        rsi = self._calculate_rsi(prices)

        # Generate signal based on RSI
        if rsi < oversold:  # Oversold
            action = "BUY"
            confidence = (oversold - rsi) / oversold
        elif rsi > overbought:  # Overbought
            action = "SELL"
            confidence = (rsi - overbought) / overbought
        else:
            action = "HOLD"
            confidence = 0.1

        size = min(1.0, confidence)

        return {"action": action, "size": size, "confidence": confidence}

    def _calculate_rsi(self, prices: List[float]) -> float:
        """Calculate RSI from price list"""
        if len(prices) < 2:
            return 50.0

        # Calculate price changes
        deltas = [prices[i] - prices[i - 1] for i in range(1, len(prices))]

        # Separate gains and losses
        gains = [max(0, delta) for delta in deltas]
        losses = [max(0, -delta) for delta in deltas]

        # Calculate average gains and losses
        avg_gain = sum(gains) / len(gains)
        avg_loss = sum(losses) / len(losses)

        if avg_loss == 0:
            return 100.0

        # Calculate RS and RSI
        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))

        return rsi

    def _breakout_strategy(self) -> Dict:
        """Breakout strategy based on price range"""
        period = self.config.get("period", 20)
        threshold = self.config.get("threshold", 0.05)

        if len(self.price_history) < period:
            return self._random_strategy()

        # Calculate price range
        prices = [p["price"] for p in self.price_history[-period:]]
        min_price = min(prices)
        max_price = max(prices)
        current_price = prices[-1]
        range_size = max_price - min_price

        if range_size == 0:
            return self._random_strategy()

        # Check for breakout
        breakout_threshold = range_size * threshold

        if current_price > max_price - breakout_threshold:  # Breakout above resistance
            action = "BUY"
            confidence = min(
                1.0,
                (current_price - (max_price - breakout_threshold)) / breakout_threshold,
            )
        elif current_price < min_price + breakout_threshold:  # Breakdown below support
            action = "SELL"
            confidence = min(
                1.0,
                ((min_price + breakout_threshold) - current_price) / breakout_threshold,
            )
        else:
            action = "HOLD"
            confidence = 0.1

        size = min(1.0, confidence * 1.5)

        return {"action": action, "size": size, "confidence": confidence}

    def _mean_reversion_strategy(self) -> Dict:
        """Mean reversion strategy"""
        period = self.config.get("period", 20)
        z_score_threshold = self.config.get("z_score_threshold", 1.0)

        if len(self.price_history) < period:
            return self._random_strategy()

        # Calculate mean and standard deviation
        prices = [p["price"] for p in self.price_history[-period:]]
        mean_price = sum(prices) / len(prices)
        std_dev = math.sqrt(sum((p - mean_price) ** 2 for p in prices) / len(prices))
        current_price = prices[-1]

        if std_dev == 0:
            return self._random_strategy()

        # Calculate z-score
        z_score = (current_price - mean_price) / std_dev

        # Generate signal based on z-score
        if (
            z_score < -z_score_threshold
        ):  # Price is below mean by more than threshold std devs
            action = "BUY"
            confidence = min(
                1.0, abs(z_score) / (z_score_threshold * 3)
            )  # Cap at 3 std devs
        elif (
            z_score > z_score_threshold
        ):  # Price is above mean by more than threshold std devs
            action = "SELL"
            confidence = min(1.0, abs(z_score) / (z_score_threshold * 3))
        else:
            action = "HOLD"
            confidence = 0.1

        size = min(1.0, confidence)

        return {"action": action, "size": size, "confidence": confidence}

    def _macd_strategy(self) -> Dict:
        """MACD strategy"""
        fast_period = self.config.get("fast_period", 12)
        slow_period = self.config.get("slow_period", 26)
        signal_period = self.config.get("signal_period", 9)

        if len(self.price_history) < slow_period + signal_period:
            return self._random_strategy()

        prices = [p["price"] for p in self.price_history[-slow_period:]]

        # Calculate MACD line (fast EMA - slow EMA)
        ema_fast = self._calculate_ema(prices[-fast_period:], fast_period)
        ema_slow = self._calculate_ema(prices, slow_period)
        macd_line = ema_fast - ema_slow

        # Calculate signal line (EMA of MACD line)
        macd_history = []
        for i in range(signal_period, len(prices)):
            hist_ema_fast = self._calculate_ema(
                prices[i - fast_period + 1 : i + 1], fast_period
            )
            hist_ema_slow = self._calculate_ema(
                prices[i - slow_period + 1 : i + 1], slow_period
            )
            macd_history.append(hist_ema_fast - hist_ema_slow)

        signal_line = (
            sum(macd_history[-signal_period:]) / signal_period
            if len(macd_history) >= signal_period
            else 0
        )

        # Generate signal based on MACD crossover
        if macd_line > signal_line:
            action = "BUY"
            confidence = min(1.0, abs(macd_line - signal_line) * 10)
        elif macd_line < signal_line:
            action = "SELL"
            confidence = min(1.0, abs(macd_line - signal_line) * 10)
        else:
            action = "HOLD"
            confidence = 0.1

        size = min(1.0, confidence)

        return {"action": action, "size": size, "confidence": confidence}

    def _calculate_ema(self, prices: List[float], period: int) -> float:
        """Calculate Exponential Moving Average"""
        if len(prices) == 0:
            return 0.0

        if len(prices) < period:
            return sum(prices) / len(prices)

        # Simple calculation for EMA
        multiplier = 2 / (period + 1)
        ema = prices[0]

        for price in prices[1:]:
            ema = (price * multiplier) + (ema * (1 - multiplier))

        return ema

    def _bollinger_bands_strategy(self) -> Dict:
        """Bollinger Bands strategy"""
        period = self.config.get("period", 20)
        std_dev = self.config.get("std_dev", 2.0)

        if len(self.price_history) < period:
            return self._random_strategy()

        prices = [p["price"] for p in self.price_history[-period:]]

        # Calculate middle band (SMA)
        middle_band = sum(prices) / len(prices)

        # Calculate standard deviation
        std_deviation = math.sqrt(
            sum((p - middle_band) ** 2 for p in prices) / len(prices)
        )

        # Calculate upper and lower bands
        upper_band = middle_band + (std_dev * std_deviation)
        lower_band = middle_band - (std_dev * std_deviation)

        current_price = prices[-1]

        # Generate signal based on price position relative to bands
        if current_price < lower_band:  # Price below lower band
            action = "BUY"
            confidence = min(1.0, (lower_band - current_price) / lower_band * 10)
        elif current_price > upper_band:  # Price above upper band
            action = "SELL"
            confidence = min(1.0, (current_price - upper_band) / upper_band * 10)
        else:
            action = "HOLD"
            confidence = 0.1

        size = min(1.0, confidence)

        return {"action": action, "size": size, "confidence": confidence}

    def set_strategy(self, strategy: str) -> None:
        """Change the active strategy"""
        self.strategy = strategy
        self.config = self._load_strategy_config()
        logger.info(f"Strategy changed to: {strategy}")

    def get_available_strategies(self) -> List[str]:
        """Get list of available strategies"""
        return [
            "random",
            "moving_average",
            "rsi",
            "breakout",
            "mean_reversion",
            "macd",
            "bollinger_bands",
        ]

    def update_config(self, config: Dict) -> bool:
        """
        Update strategy configuration

        Args:
            config: New configuration

        Returns:
            True if successful, False otherwise
        """
        self.config = config
        return self._save_strategy_config(config)
